name: flutter_application_9
description: "University Guide Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.0
  provider: ^6.1.2

  cupertino_icons: ^1.0.8

  eva_icons_flutter: ^3.1.0
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/fonts/
    - assets/sql/
    - assets/universities/

  # Fonts
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

    - family: Tajawal
    
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
